services:
  L4D2:
    container_name: L4D2
    env_file:
      - .env
    environment:
        - TZ=${TZ:-Europe/Brussels}
        - COLLECTIONS=${COLLECTIONS:-2787147130 2805134338}
        - SERVER_NAME=${SERVER_NAME:-Left4Friends 1 - Be Kind}
        - SRCDS_PORT=${SRCDS_PORT:-27025}
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - HOST_LEFT4DEAD2_PATH=${HOST_LEFT4DEAD2_PATH:-/opt/docker/L4D2}   

    # ports:
    #   - 27025:27025
    #   - 27025:27025/udp
    network_mode: host
    image: ghcr.io/esdeka/l4d2serverresources:latest
    restart: unless-stopped
    volumes:
      - ${HOST_LEFT4DEAD2_PATH}:/home/steam/left4dead2:rw
    stdin_open: true # docker run -i
    tty:        true # docker run -t
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    # entrypoint: /bin/bash   #debugging
networks: {}